PerformanceAndResilience/1_lab/WebApplication/Models/EditCustomerViewModel.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace WebApplication.Models
{
    public class EditCustomerViewModel
    {
        [Required]
        public int CustomerID { get; set; }

        [DisplayName("Name style")]
        public bool NameStyle { get; set; }

        public string Title { get; set; }

        [DisplayName("First name")]
        public string FirstName { get; set; }

        [DisplayName("Middle name")]
        public string MiddleName { get; set; }

        [Required]
        [DisplayName("Last name")]
        public string LastName { get; set; }

        [DisplayName("Suffix")]
        public string Suffix { get; set; }

        [DisplayName("Company name")]
        public string CompanyName { get; set; }

        [DisplayName("Sales person")]
        public string SalesPerson { get; set; }

        [EmailAddress]
        [DisplayName("Email address")]
        public string EmailAddress { get; set; }

        [Phone]
        [DisplayName("Phone number")]
        public string Phone { get; set; }
    }
}

PerformanceAndResilience/1_lab/WebApplication/Models/ErrorViewModel.cs
using System;

namespace WebApplication.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

PerformanceAndResilience/1_lab/WebApplication/Models/ViewAllCustomersViewModel.cs
using System.Collections.Generic;
using WebApplication.DataModels;

namespace WebApplication.Models
{
    public class ViewAllCustomersViewModel
    {
        public IReadOnlyList<Customer> Customers { get; set; }
    }
}

PerformanceAndResilience/1_lab/WebApplication/Controllers/CustomerController.cs
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using System.Threading.Tasks;
using WebApplication.DataModels;
using WebApplication.Models;
using WebApplication.Services;

namespace WebApplication.Controllers
{
    public class CustomerController : Controller
    {
        public CustomerController(
            ICustomerService customerService)
        {
            this.CustomerService = customerService;
        }

        private ICustomerService CustomerService { get; }


        public async Task<IActionResult> Index()
        {
            var allCustomers = await this.CustomerService.GetAllCustomersAsync();

            var model = new ViewAllCustomersViewModel
            {
                Customers = allCustomers.ToList(),
            };

            return View(model);
        }

        public async Task<IActionResult> Edit(string id)
        {
            long customerId = long.Parse(id);

            var customer = await this.CustomerService.GetCustomerAsync(customerId);

            var model = new EditCustomerViewModel
            {
                CustomerID = customer.CustomerID,
                NameStyle = customer.NameStyle,
                Title = customer.Title,
                FirstName = customer.FirstName,
                MiddleName = customer.MiddleName,
                LastName = customer.LastName,
                Suffix = customer.Suffix,
                CompanyName = customer.CompanyName,
                SalesPerson = customer.SalesPerson,
                EmailAddress = customer.EmailAddress,
                Phone = customer.Phone,
            };

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(EditCustomerViewModel model)
        {
            if (ModelState.IsValid)
            {
                long customerId = model.CustomerID;

                Customer customer = await this.CustomerService.GetCustomerAsync(customerId);

                bool hasChanges = false;

                if (!Equals(customer.NameStyle, model.NameStyle))
                {
                    hasChanges = true;
                    customer.NameStyle = model.NameStyle;
                }

                if (!Equals(customer.Title, model.Title))
                {
                    hasChanges = true;
                    customer.Title = model.Title;
                }

                if (!Equals(customer.FirstName, model.FirstName))
                {
                    hasChanges = true;
                    customer.FirstName = model.FirstName;
                }

                if (!Equals(customer.MiddleName, model.MiddleName))
                {
                    hasChanges = true;
                    customer.MiddleName = model.MiddleName;
                }

                if (!Equals(customer.LastName, model.LastName))
                {
                    hasChanges = true;
                    customer.LastName = model.LastName;
                }

                if (!Equals(customer.Suffix, model.Suffix))
                {
                    hasChanges = true;
                    customer.Suffix = model.Suffix;
                }

                if (!Equals(customer.CompanyName, model.CompanyName))
                {
                    hasChanges = true;
                    customer.CompanyName = model.CompanyName;
                }

                if (!Equals(customer.SalesPerson, model.SalesPerson))
                {
                    hasChanges = true;
                    customer.SalesPerson = model.SalesPerson;
                }

                if (!Equals(customer.EmailAddress, model.EmailAddress))
                {
                    hasChanges = true;
                    customer.EmailAddress = model.EmailAddress;
                }

                if (!Equals(customer.Phone, model.Phone))
                {
                    hasChanges = true;
                    customer.Phone = model.Phone;
                }


                if (hasChanges)
                {
                    await this.CustomerService.UpdateCustomerAsync(customer);
                }

                return RedirectToAction(nameof(Index));
            }

            return View(model);
        }

        public async Task<IActionResult> Delete(string id)
        {
            long customerId = long.Parse(id);

            await this.CustomerService.DeleteCustomerAsync(customerId);

            return RedirectToAction(nameof(Index));
        }
    }
}

PerformanceAndResilience/1_lab/WebApplication/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using WebApplication.Models;

namespace WebApplication.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

PerformanceAndResilience/1_lab/WebApplication/Views/Customer/Edit.cshtml
@using WebApplication.Models;
@model EditCustomerViewModel

<div class="text-center">
    <h1 class="display-4">Customer - @Html.DisplayFor(m => m.CustomerID)</h1>
</div>

<form asp-controller="Customer" asp-action="Edit" method="post">
    @Html.ValidationSummary()
    <input class="text form-control" asp-for="CustomerID" type="hidden" />

    <div class="form-check">
        <input class="form-check-input" asp-for="NameStyle" />
        <label class="form-check-label" asp-for="NameStyle"></label>
        <span asp-validation-for="NameStyle"></span>
    </div>

    <div class="form-group">
        <label asp-for="Title"></label>
        <input class="form-control" asp-for="Title" />
        <span asp-validation-for="Title"></span>
    </div>

    <div class="form-group">
        <label asp-for="FirstName"></label>
        <input class="form-control" asp-for="FirstName" />
        <span asp-validation-for="FirstName"></span>
    </div>

    <div class="form-group">
        <label asp-for="MiddleName"></label>
        <input class="form-control" asp-for="MiddleName" />
        <span asp-validation-for="MiddleName"></span>
    </div>

    <div class="form-group">
        <label asp-for="LastName"></label>
        <input class="form-control" asp-for="LastName" />
        <span asp-validation-for="LastName"></span>
    </div>

    <div class="form-group">
        <label asp-for="Suffix"></label>
        <input class="form-control" asp-for="Suffix" />
        <span asp-validation-for="Suffix"></span>
    </div>

    <div class="form-group">
        <label asp-for="CompanyName"></label>
        <input class="form-control" asp-for="CompanyName" />
        <span asp-validation-for="CompanyName"></span>
    </div>

    <div class="form-group">
        <label asp-for="SalesPerson"></label>
        <input class="form-control" asp-for="SalesPerson" />
        <span asp-validation-for="SalesPerson"></span>
    </div>

    <div class="form-group">
        <label asp-for="EmailAddress"></label>
        <input class="form-control" asp-for="EmailAddress" />
        <span asp-validation-for="EmailAddress"></span>
    </div>

    <div class="form-group">
        <label asp-for="Phone"></label>
        <input class="form-control" asp-for="Phone" />
        <span asp-validation-for="Phone"></span>
    </div>

    <div class="row">
        <div class="col-12 col-md-2">
            <button type="button" class="btn btn-outline-danger btn-block" data-toggle="modal" data-target="#deleteConfirmationModal">
                Delete
            </button>
        </div>
        <div class="col-6"></div>
        <div class="col-12 col-md-2">
            <a asp-action="Index" asp-controller="Customer" class="btn btn-block">Cancel</a>
        </div>
        <div class="col-12 col-md-2">
            <input type="submit" name="submit" value="Save" class="btn btn-primary btn-block" />
        </div>
    </div>

</form>

<div class="modal fade" id="deleteConfirmationModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Delete Customer</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                Deleting a customer is permanent and you will not be able to recover. Do you wish to go proceed?
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                <a asp-action="Delete" asp-controller="Customer" asp-route-id="@Model.CustomerID" class="btn btn-danger">Delete</a>
            </div>
        </div>
    </div>
</div>

PerformanceAndResilience/1_lab/WebApplication/Views/Customer/Index.cshtml
@using WebApplication.DataModels;
@using WebApplication.Models;
@model ViewAllCustomersViewModel

<div class="text-center">
    <h1 class="display-4">All customers</h1>


    <table class="table table-striped table-hover">
        <thead class="thead-light">
            <tr>
                <th scope="col">#</th>
                <th scope="col">First</th>
                <th scope="col">Last</th>
            </tr>
        </thead>
        <tbody>
            @foreach (Customer customer in Model.Customers)
            {
            <tr>
                <th scope="row">@Html.ActionLink(customer.CustomerID.ToString(), "Edit", "Customer", new { id = customer.CustomerID })</th>
                <td>@Html.ActionLink(customer.FirstName, "Edit", "Customer", new { id = customer.CustomerID })</td>
                <td>@Html.ActionLink(customer.LastName, "Edit", "Customer", new { id = customer.CustomerID })</td>
            </tr>
            }
        </tbody>
    </table>
</div>

PerformanceAndResilience/1_lab/WebApplication/Views/Home/Index.cshtml
<div class="text-center">
    <h1>Resilience Lab</h1>
    <h2></h2>
</div>

PerformanceAndResilience/1_lab/WebApplication/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebApplication</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">WebApplication</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <!-- Insert navigation links here -->
                    <li><a asp-area="" asp-controller="Customer" asp-action="Index">All Customers</a></li>
                </ul>
            </div>
        </div>
    </nav>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2019 - WebApplication</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>